---
apt_cli_packages:
  - stow
  - zsh
  - neovim
  - imagemagick
  - neofetch
  - bat
  - autojump
  - tmux
  - fzf
  - ripgrep
  - lsd
  - mupdf
  - htop
  - silversearcher-ag
  - openssh-server
  - rsync
  - ranger
  - w3m
  - wget
  - pip

start_services:
  - sshd

home_dir: "/root"
dotfiles_repo_name: "Dotfiles"
dotfiles_repo_link: "https://github.com/4542elgh/Dotfiles_Ansible"

node_red:
  repo: "https://github.com/node-red/node-red.git"
  dir: "/root/node-red"
  service_name: "nodered"
  dependencies:
    apt:
      - git
      - npm
    npm:
      - grunt-cli
