---
- name: "Update system"
  hosts: "all"
  tasks:
  - name: "Update system MacOSX"
    block:
    - name: "Display message"
      debug:
        msg: "This operation will likely take a while"
    - name: Update homebrew packages
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
    when: ansible_pkg_mgr is defined and ansible_pkg_mgr == "homebrew"