---
- name: "Setup Debian based DE"
  hosts: vm
  tasks:
    - name: "Set system identifier"
      set_fact:
        system_identifier: "{{ansible_facts.system}}_{{ansible_facts.distribution}}"

    - name: "Include vars"
      include_vars:
        file: "group_vars/{{system_identifier}}.yml"

    - name: "Install CLI app based on OS"
      include_tasks:
        file: "tasks/{{system_identifier}}_CLI.yml"

    - name: "Install docker"
      include_tasks:
        file: "tasks/{{system_identifier}}/get_docker.yml"