---
- name: "Install pacman packages"
  pacman:
    name: "{{pacman_cli_packages}}"
    state: present
  become: true

- name: "Get yay"
  include_tasks:
    file: "Linux_Arch/get_yay.yml"

- name: "Install yay packages"
  yay:
    name: "{{yay_cli_packages}}"
    state: present

- name: "Generate man pages"
  shell: "mandb"

- name: "Make sure services are running"
  systemd:
    name: "{{item}}"
    state: started
    enabled: true
  loop: "{{start_services}}"

