---
- name: "Check if {{binary_name}} is installed"
  shell: "which {{binary_name}}"
  changed_when: false
  failed_when: binary_exists.rc not in [0,1]
  register: binary_exists
  
- name: "Set fact"
  set_fact:
    stat:
      name: "{{binary_name}}"
      exists : "{{binary_exists.rc == 0}}"
