---
- name: Check if a share folder exist, if it does skip mapping
  ansible.windows.win_command:
    cmd: '"cmd.exe" "if exist t:\ ( echo true ) else ( echo false)"'
  register: share_exists

- name: Create mapped drive with credentials and save the username and password
  block:
  - name: Save the network credentials required for the mapped drive
    community.windows.win_credential:
      name: 192.168.1.31
      type: generic_password
      username: evan
      secret: ''
      state: present

  - name: Save the network credentials required for the mapped drive
    community.windows.win_credential:
      name: 10.10.10.31
      type: generic_password
      username: evan
      secret: ''
      state: present

  - name: Create a mapped drive under T
    community.windows.win_mapped_drive:
      letter: "{{ item.letter }}"
      path: "{{ item.path }}"
      state: present
    loop: {{smb_shares}}
  become_method: runas
  become_user: 4542e
  when: not share_exists
  become: true
