---
- name: "Check yay exists"
  include_role:
    name: binary_exists
  vars:
    binary_name: "yay"
  register: yay_stat

- name: "Check git exists"
  include_role:
    name: binary_exists
  vars:
    binary_name: "git"
  register: git_stat

- name: "Check makepkg exists"
  include_role:
    name: binary_exists
  vars:
    binary_name: "makepkg"
  register: makepkg_stat

- name: "Install yay"
  block:
    - name: "Get yay git"
      git:
        repo: "https://aur.archlinux.org/yay.git"
        dest: "/tmp/yay"
        version: "next"
        update: "no"

    - name: "Build yay"
      shell: "makepkg --noconfirm -si"
      args:
        chdir: "/tmp/yay"

    - name: "Delete /tmp/yay"
      file:
        path: "/tmp/yay"
        state: absent
  when: not yay_stat.exists and git_stat.exists and makepkg_stat.exists